# Generated by Django 3.2.8 on 2022-01-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('event_type', models.CharField(max_length=30)),
                ('event_time', models.CharField(max_length=30)),
                ('event_date', models.CharField(max_length=30)),
                ('sport_category', models.CharField(max_length=30)),
                ('sport_type', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('skill', models.CharField(max_length=30)),
                ('position_price', models.CharField(max_length=30)),
                ('max_age', models.CharField(max_length=30)),
                ('min_age', models.CharField(max_length=30)),
                ('venue', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
    ]
