# Generated by Django 3.2.12 on 2022-04-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
