# Generated by Django 3.2.12 on 2023-03-10 03:38

import EventsApp.validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[EventsApp.validator.image_restriction]),
        ),
    ]
