# Generated by Django 3.2.12 on 2022-12-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_auto_20221220_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='header',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
