# Generated by Django 3.2.12 on 2022-04-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0002_alter_master_table_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='individual',
            name='concussion',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='dob',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='participation_interest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='provider',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sports_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sports_position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sports_skill',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='sports_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
