# Generated by Django 3.2.8 on 2022-01-12 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0003_auto_20220112_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='event_type',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='max_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='min_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
