# Generated by Django 3.2.12 on 2022-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0003_auto_20220412_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individual',
            name='concussion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
