# Generated by Django 3.2.12 on 2023-03-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0003_ad_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionandskilltype',
            name='skill_rank',
            field=models.IntegerField(default=0),
        ),
    ]
