# Generated by Django 3.2.8 on 2021-11-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_auto_20211111_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=20, verbose_name='Category'),
        ),
    ]
