# Generated by Django 3.2.8 on 2022-01-12 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_auto_20220112_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='master_table',
            name='position_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Test_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('test_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.test_city')),
                ('test_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.master_table')),
            ],
        ),
        migrations.AddField(
            model_name='test_city',
            name='test_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.master_table'),
        ),
    ]
