# Generated by Django 3.2.12 on 2022-04-13 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0004_alter_individual_concussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_person',
            name='test_city',
        ),
        migrations.RemoveField(
            model_name='test_person',
            name='test_country',
        ),
        migrations.DeleteModel(
            name='Test_City',
        ),
        migrations.DeleteModel(
            name='Test_Person',
        ),
    ]
