# Generated by Django 3.2.8 on 2022-01-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0005_auto_20220112_2359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master_table',
            old_name='event_date',
            new_name='datetimes',
        ),
        migrations.RemoveField(
            model_name='master_table',
            name='event_time',
        ),
        migrations.RemoveField(
            model_name='master_table',
            name='name',
        ),
        migrations.AddField(
            model_name='master_table',
            name='no_of_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='position_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='event_type',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
