# Generated by Django 3.2.8 on 2021-11-15 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0005_event_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='multistepform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(max_length=120, verbose_name='Event Name')),
                ('description', models.CharField(max_length=120, verbose_name='Event Name')),
                ('category', models.CharField(max_length=120, verbose_name='Event Name')),
                ('venue', models.CharField(max_length=120, verbose_name='Event Name')),
                ('manager', models.CharField(max_length=120, verbose_name='Event Name')),
                ('phone', models.CharField(max_length=120, verbose_name='Event Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
        ),
    ]
