# Generated by Django 3.2.12 on 2022-04-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0005_auto_20220412_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='first_name',
            new_name='age_group',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='last_name',
            new_name='email',
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='gender_focus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='parent_organization_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='registration_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='type_of_organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='year_established',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
