# Generated by Django 3.2.12 on 2022-04-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0006_auto_20220413_0049'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsappTestPerson',
        ),
    ]
