# Generated by Django 3.2.8 on 2021-11-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0006_multistepform'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStepFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=120, verbose_name='Event Name')),
                ('event_date', models.DateTimeField(max_length=120, verbose_name='Event Date')),
                ('description', models.CharField(max_length=120, verbose_name='description')),
                ('category', models.CharField(max_length=120, verbose_name='category')),
                ('venue', models.CharField(max_length=120, verbose_name='venue')),
                ('manager', models.CharField(max_length=120, verbose_name='manager')),
                ('phone', models.CharField(max_length=120, verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
            ],
        ),
        migrations.DeleteModel(
            name='multistepform',
        ),
    ]
