# Generated by Django 3.2.12 on 2023-04-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0006_remove_user_active_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('In-Person', 'In-Person'), ('Online', 'Online'), ('Both', 'Both')], default='In-Person', max_length=300, null=True),
        ),
    ]
