# Generated by Django 3.2.8 on 2022-01-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0007_auto_20220114_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='datetimes',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
