# Generated by Django 3.2.12 on 2022-04-14 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0007_delete_eventsapptestperson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsSportsPosition',
        ),
        migrations.DeleteModel(
            name='IsSportsProficiency',
        ),
    ]
