# Generated by Django 3.2.12 on 2023-04-18 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0007_master_table_venue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='event_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
