# Generated by Django 3.2.8 on 2021-11-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0007_auto_20211118_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=120, verbose_name='Event Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('event_type', models.CharField(max_length=20, verbose_name='Event Type')),
                ('min_age', models.CharField(max_length=20, verbose_name='Minimum Age')),
                ('max_age', models.CharField(max_length=20, verbose_name='Maximum Age')),
                ('sport_type', models.CharField(max_length=200, verbose_name='Sport Type')),
                ('venue', models.CharField(max_length=120, verbose_name='Venue')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('city', models.CharField(max_length=120, verbose_name='City')),
                ('province', models.CharField(max_length=120, verbose_name='Province')),
                ('country', models.CharField(max_length=120, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=120, verbose_name='Zip')),
            ],
        ),
    ]
