# Generated by Django 3.2.8 on 2021-11-20 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0008_multiform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistepformmodel',
            name='venue',
        ),
        migrations.AlterField(
            model_name='multiform',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='country',
            field=models.CharField(blank=True, max_length=120, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='max_age',
            field=models.IntegerField(max_length=20, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='min_age',
            field=models.IntegerField(max_length=20, verbose_name='Minimum Age'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='province',
            field=models.CharField(blank=True, max_length=120, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsApp.venue'),
        ),
        migrations.AlterField(
            model_name='multiform',
            name='zip_code',
            field=models.CharField(blank=True, max_length=120, verbose_name='Zip'),
        ),
    ]
