# Generated by Django 3.2.12 on 2022-04-14 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0008_auto_20220414_1740'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsSportsCategory',
        ),
        migrations.DeleteModel(
            name='IsSportsDetails',
        ),
    ]
