# Generated by Django 3.2.12 on 2023-05-12 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0008_master_table_event_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='is_third_party',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=300, null=True),
        ),
    ]
