# Generated by Django 3.2.12 on 2022-04-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0009_auto_20220414_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_catgeory_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SportsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_type_text', models.CharField(max_length=100)),
                ('sports_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.sportscategory')),
            ],
        ),
    ]
