# Generated by Django 3.2.8 on 2021-11-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0009_auto_20211120_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiform',
            name='sport_type',
            field=models.DateTimeField(verbose_name='sport_type'),
        ),
    ]
