# Generated by Django 3.2.12 on 2022-04-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0010_sportscategory_sportstype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vm_venue_description', models.CharField(blank=True, max_length=250, null=True)),
                ('vm_venue_street', models.CharField(blank=True, max_length=250, null=True)),
                ('vm_venuecity', models.CharField(blank=True, max_length=50, null=True)),
                ('vm_venue_province', models.CharField(blank=True, max_length=50, null=True)),
                ('vm_venue_country', models.CharField(blank=True, max_length=50, null=True)),
                ('vm_venue_zip', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='IsVenueMaster',
        ),
    ]
