# Generated by Django 3.2.9 on 2022-02-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0010_auto_20220205_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsEventTypeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etm_id', models.IntegerField()),
                ('etm_category', models.CharField(blank=True, max_length=100, null=True)),
                ('etm_title', models.CharField(blank=True, max_length=100, null=True)),
                ('etm_description', models.CharField(blank=True, max_length=250, null=True)),
                ('etm_isactive', models.CharField(blank=True, max_length=1, null=True)),
                ('etm_created_by', models.IntegerField(blank=True, null=True)),
                ('etm_updated_by', models.IntegerField(blank=True, null=True)),
                ('etm_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'is_event_type_master',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='is_event_type_master',
        ),
    ]
