# Generated by Django 3.2.8 on 2021-11-20 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0010_alter_multiform_sport_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=120, verbose_name='Event Title')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('event_type', models.CharField(max_length=20, verbose_name='Event Type')),
                ('min_age', models.IntegerField(max_length=20, verbose_name='Minimum Age')),
                ('max_age', models.IntegerField(max_length=20, verbose_name='Maximum Age')),
                ('sport_type', models.DateTimeField(verbose_name='sport_type')),
                ('street', models.CharField(blank=True, max_length=120, verbose_name='Street')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=120, verbose_name='Province')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Country')),
                ('zip_code', models.CharField(blank=True, max_length=120, verbose_name='Zip Code')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsApp.venue')),
            ],
        ),
        migrations.DeleteModel(
            name='MultiForm',
        ),
    ]
