# Generated by Django 3.2.8 on 2021-11-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0011_auto_20211120_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='max_age',
            field=models.IntegerField(verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='min_age',
            field=models.IntegerField(verbose_name='Minimum Age'),
        ),
    ]
