# Generated by Django 3.2.12 on 2022-04-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0011_auto_20220415_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venues',
            name='vm_venue_zip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
