# Generated by Django 3.2.8 on 2021-11-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0012_auto_20211120_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='max_age',
            field=models.CharField(blank=True, max_length=120, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='min_age',
            field=models.CharField(blank=True, max_length=120, verbose_name='Minimum Age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='sport_type',
            field=models.CharField(blank=True, max_length=120, verbose_name='sport_type'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='venue',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Venue'),
        ),
    ]
