# Generated by Django 3.2.12 on 2022-04-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0013_auto_20220415_2019'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsSportsMaster',
        ),
    ]
