# Generated by Django 3.2.8 on 2021-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0013_auto_20211120_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistep',
            name='sport_type',
        ),
        migrations.AddField(
            model_name='multistep',
            name='date',
            field=models.CharField(blank=True, max_length=120, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='end_time',
            field=models.CharField(blank=True, max_length=120, verbose_name='End Time'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='start_time',
            field=models.CharField(blank=True, max_length=120, verbose_name='Start Time'),
        ),
    ]
