# Generated by Django 3.2.8 on 2021-11-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0014_auto_20211120_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='date',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
    ]
