# Generated by Django 3.2.12 on 2022-04-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0015_auto_20220415_2030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsEventsMaster',
        ),
    ]
