# Generated by Django 3.2.8 on 2021-11-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0015_alter_multistep_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='multistep',
            name='category',
            field=models.CharField(default='SOME STRING', max_length=120, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.CharField(max_length=20, verbose_name='Free/Fee'),
        ),
    ]
