# Generated by Django 3.2.8 on 2021-11-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0016_auto_20211124_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='end_time',
            field=models.DurationField(null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='start_time',
            field=models.DurationField(null=True, verbose_name='Start Time'),
        ),
    ]
