# Generated by Django 3.2.12 on 2022-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0017_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
