# Generated by Django 3.2.8 on 2021-12-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0017_auto_20211129_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='end_time',
            field=models.CharField(max_length=120, null=True, verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='start_time',
            field=models.CharField(max_length=120, null=True, verbose_name='Start Time'),
        ),
    ]
