# Generated by Django 3.2.8 on 2021-12-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0018_auto_20211213_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistep',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='multistep',
            name='min_age',
        ),
        migrations.AddField(
            model_name='multistep',
            name='ath_max_age',
            field=models.CharField(blank=True, max_length=120, verbose_name='Athelete Maximum Age'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='ath_min_age',
            field=models.CharField(blank=True, max_length=120, verbose_name='Athelete Minimum Age'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='athelete_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Athelete Level'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='staff_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='Staff Level'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='sup_max_age',
            field=models.CharField(blank=True, max_length=120, verbose_name='Support Maximum Age'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='sup_min_age',
            field=models.CharField(blank=True, max_length=120, verbose_name='Support Minimum Age'),
        ),
    ]
