# Generated by Django 3.2.8 on 2021-12-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0019_auto_20211219_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multistep',
            name='date',
        ),
        migrations.RemoveField(
            model_name='multistep',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='multistep',
            name='start_time',
        ),
        migrations.AddField(
            model_name='multistep',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='multistep',
            name='event_time',
            field=models.CharField(max_length=20, null=True, verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='ath_max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='ath_min_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='athelete_level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Athelete Level'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='category',
            field=models.CharField(default='SOME STRING', max_length=30, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='event_title',
            field=models.CharField(max_length=30, null=True, verbose_name='Event Title'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.CharField(max_length=20, null=True, verbose_name='Free/Fee'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='province',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='staff_level',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Staff Level'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='street',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='sup_max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='sup_min_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='venue',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='zip_code',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Zip Code'),
        ),
    ]
