# Generated by Django 3.2.12 on 2022-05-09 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0019_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='event_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
