# Generated by Django 3.2.12 on 2022-05-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0020_alter_master_table_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Camp', 'Camp'), ('Charity', 'Charity'), ('Conditioning', 'Conditioning'), ('Development', 'Development'), ('Game/Session', 'Game/Session'), ('Online', 'Online'), ('Registration', 'Registration'), ('Social', 'Social'), ('Tournament', 'Tournament')], max_length=50, null=True),
        ),
    ]
