# Generated by Django 3.2.8 on 2021-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0020_auto_20211229_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
