# Generated by Django 3.2.8 on 2021-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0021_alter_multistep_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='ath_max_age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='ath_min_age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='sup_max_age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='sup_min_age',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
