# Generated by Django 3.2.12 on 2022-05-16 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0022_alter_availability_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
