# Generated by Django 3.2.8 on 2022-01-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0022_auto_20211229_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='MultiStepFormModel',
        ),
        migrations.AlterField(
            model_name='multistep',
            name='ath_min_age',
            field=models.CharField(max_length=20, null=True, verbose_name='Athelete mininum age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='description',
            field=models.TextField(max_length=200, null=True, verbose_name='Description'),
        ),
    ]
