# Generated by Django 3.2.12 on 2022-05-12 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0018_user_password_reset_token'),
        ('EventsApp', '0022_alter_availability_day_of_week'),
    ]

    operations = [
    ]
