# Generated by Django 3.2.8 on 2022-01-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0024_auto_20220104_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Free/Fee'),
        ),
    ]
