# Generated by Django 3.2.12 on 2022-05-19 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0024_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventsApp.master_table'),
        ),
    ]
