# Generated by Django 3.2.12 on 2022-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0025_extra_loctaions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventsappTestCity',
        ),
    ]
