# Generated by Django 3.2.8 on 2022-01-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0026_auto_20220106_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='multistep',
            name='category',
            field=models.CharField(blank=True, max_length=30, verbose_name='Sport Category'),
        ),
    ]
