# Generated by Django 3.2.8 on 2022-01-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0027_auto_20220106_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='category',
            new_name='name',
        ),
    ]
