# Generated by Django 3.2.8 on 2022-01-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0028_auto_20220106_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.country'),
        ),
    ]
