# Generated by Django 3.2.12 on 2022-05-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0029_auto_20220517_1817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsEventsScheduler',
        ),
    ]
