# Generated by Django 3.2.8 on 2022-01-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0030_alter_city_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='country',
            new_name='sport_category',
        ),
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RenameModel(
            old_name='Country',
            new_name='SportCategory',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.sportcategory'),
        ),
        migrations.AddField(
            model_name='person',
            name='skill_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.skill'),
        ),
    ]
