# Generated by Django 3.2.12 on 2022-05-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0030_delete_iseventsscheduler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IsNotificationMaster',
        ),
    ]
