# Generated by Django 3.2.12 on 2022-05-17 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0031_delete_isnotificationmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secondary_SportsChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_entry_number', models.IntegerField(blank=True, null=True)),
                ('sport_category', models.CharField(blank=True, max_length=30, null=True)),
                ('sport_type', models.CharField(blank=True, max_length=30, null=True)),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
