# Generated by Django 3.2.8 on 2022-01-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0031_auto_20220106_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='person',
            old_name='sport_category',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='person',
            name='skill_level',
        ),
        migrations.RenameModel(
            old_name='SportCategory',
            new_name='Country',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='EventsApp.city'),
        ),
    ]
