# Generated by Django 3.2.12 on 2022-05-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0032_secondary_sportschoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_positioninfo',
            name='position_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
