# Generated by Django 3.2.8 on 2022-01-06 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0033_auto_20220106_2219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportType',
            new_name='Sport_type',
        ),
    ]
