# Generated by Django 3.2.12 on 2022-05-26 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0025_alter_invite_event'),
        ('EventsApp', '0034_cart'),
    ]

    operations = [
    ]
