# Generated by Django 3.2.8 on 2022-01-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0034_rename_sporttype_sport_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='city',
        ),
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.RemoveField(
            model_name='position',
            name='sport_type',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='sport_type',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sportcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sportcategory',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='sportcategory',
            name='sport_type',
        ),
        migrations.RemoveField(
            model_name='multistep',
            name='sport_name',
        ),
        migrations.AddField(
            model_name='multistep',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='max_age',
            field=models.IntegerField(null=True, verbose_name='Maximum Age'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='min_age',
            field=models.IntegerField(null=True, verbose_name='Minimum Age'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='position',
            field=models.CharField(max_length=30, null=True, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='position_price',
            field=models.IntegerField(null=True, verbose_name='Position Price'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='skill',
            field=models.CharField(max_length=30, null=True, verbose_name='Skill Level'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='sport_category',
            field=models.CharField(max_length=30, null=True, verbose_name='Sport Category'),
        ),
        migrations.AddField(
            model_name='multistep',
            name='sport_type',
            field=models.CharField(max_length=30, null=True, verbose_name='Sport Type'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='event_date',
            field=models.DateTimeField(null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.IntegerField(null=True, verbose_name='Event Type'),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='Sport_type',
        ),
        migrations.DeleteModel(
            name='SportCategory',
        ),
    ]
