# Generated by Django 3.2.8 on 2022-01-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0035_auto_20220107_0327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='description',
            field=models.CharField(max_length=200, null=True, verbose_name='Description'),
        ),
    ]
