# Generated by Django 3.2.12 on 2022-05-29 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0036_auto_20220526_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_table',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='master_table',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='invite',
            name='invite_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 12, 34, 29, 716251)),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
