# Generated by Django 3.2.8 on 2022-01-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0036_alter_multistep_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_date',
            field=models.DateField(null=True, verbose_name='Event Date'),
        ),
    ]
