# Generated by Django 3.2.12 on 2022-05-29 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0037_auto_20220529_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='datetimes_exceptions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_friday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_monday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_saturday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_sunday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_thursday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_tuesday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='datetimes_wednesday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='is_recurring',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invite',
            name='invite_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='datetimes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
