# Generated by Django 3.2.12 on 2022-06-07 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0037_auto_20220531_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='provider',
        ),
    ]
