# Generated by Django 3.2.12 on 2022-06-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0038_remove_individual_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionAndSkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_type', models.CharField(max_length=100)),
                ('skill_type', models.CharField(max_length=100)),
                ('sports_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.sportscategory')),
                ('sports_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventsApp.sportstype')),
            ],
        ),
    ]
