# Generated by Django 3.2.8 on 2022-01-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0038_auto_20220107_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.IntegerField(default=0, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='max_age',
            field=models.IntegerField(default=0, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='min_age',
            field=models.IntegerField(default=0, null=True, verbose_name='Minimum Age'),
        ),
    ]
