# Generated by Django 3.2.12 on 2022-06-16 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0039_positionandskilltype'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='is_student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
