# Generated by Django 3.2.12 on 2022-06-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0040_individual_is_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondary_sportschoice',
            name='sport_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
