# Generated by Django 3.2.8 on 2022-01-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0040_auto_20220107_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Event Type'),
        ),
    ]
