# Generated by Django 3.2.12 on 2022-06-29 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0041_alter_secondary_sportschoice_sport_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mvp',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
