# Generated by Django 3.2.8 on 2022-01-07 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0041_alter_multistep_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='position_price',
            field=models.CharField(max_length=30, null=True, verbose_name='Position Price'),
        ),
    ]
