# Generated by Django 3.2.12 on 2022-07-09 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0042_auto_20220630_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master_table',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='master_table',
            name='sport_category',
        ),
    ]
