# Generated by Django 3.2.12 on 2022-06-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0042_user_is_mvp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='city',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='country',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='event_title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Camp', 'Camp'), ('Charity', 'Charity'), ('Conditioning', 'Conditioning'), ('Development', 'Development'), ('Game/Session', 'Game/Session'), ('Online', 'Online'), ('Registration', 'Registration'), ('Social', 'Social'), ('Tournament', 'Tournament')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='province',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='skill',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='sport_category',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='sport_type',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='master_table',
            name='venue',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
