# Generated by Django 3.2.8 on 2022-01-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0043_auto_20220107_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event Date'),
        ),
    ]
