# Generated by Django 3.2.12 on 2022-07-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0043_auto_20220709_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
