# Generated by Django 3.2.12 on 2022-07-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0044_individual_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secondary_sportschoice',
            name='sport_category',
        ),
    ]
