# Generated by Django 3.2.8 on 2022-01-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0044_alter_multistep_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
    ]
