# Generated by Django 3.2.12 on 2022-07-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0046_secondary_sportschoice_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='gender',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
