# Generated by Django 3.2.8 on 2022-01-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0046_alter_multistep_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multistep',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='event_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='max_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Maximum Age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='min_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Age'),
        ),
        migrations.AlterField(
            model_name='multistep',
            name='position_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Position Price'),
        ),
    ]
