# Generated by Django 3.2.12 on 2022-07-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0047_master_table_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='master_table',
            name='zipcode',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
