# Generated by Django 3.2.12 on 2022-07-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0048_auto_20220717_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
        ),
    ]
