# Generated by Django 3.2.12 on 2022-07-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0049_sportsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportsimage',
            name='sport',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
