# Generated by Django 3.2.12 on 2022-07-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0050_alter_sportsimage_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='sport_logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
