# Generated by Django 3.2.12 on 2022-07-20 17:53

import EventsApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0051_master_table_sport_logo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', EventsApp.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
