# Generated by Django 3.2.12 on 2022-07-31 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0053_auto_20220720_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_positioninfo',
            name='position_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
