# Generated by Django 3.2.12 on 2022-07-29 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0053_auto_20220720_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extra_loctaions',
            name='location_number',
        ),
        migrations.RemoveField(
            model_name='secondary_sportschoice',
            name='sport_entry_number',
        ),
    ]
