# Generated by Django 3.2.12 on 2022-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0054_events_positioninfo_position_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='individual',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
