# Generated by Django 3.2.12 on 2022-08-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0054_auto_20220729_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_positioninfo',
            name='position_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='job_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
