# Generated by Django 3.2.12 on 2022-08-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0055_auto_20220802_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='extra_loctaions',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='extra_loctaions',
            name='zipcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
