# Generated by Django 3.2.12 on 2022-08-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0058_organization_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
