# Generated by Django 3.2.12 on 2022-08-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0060_rename_cart_orderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='event',
        ),
    ]
