# Generated by Django 3.2.12 on 2022-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0061_remove_order_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='EventsApp.OrderItems'),
        ),
    ]
