# Generated by Django 3.2.12 on 2022-08-16 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0062_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='skill',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
