# Generated by Django 3.2.12 on 2022-08-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0071_alter_orderitems_checkout_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Cash Pickup', 'Cash Pickup'), ('Card', 'Card')], default='--Select--', max_length=20),
        ),
    ]
