# Generated by Django 3.2.12 on 2022-09-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0072_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_positioninfo',
            name='position_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
