# Generated by Django 3.2.12 on 2022-09-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0073_alter_events_positioninfo_position_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='position_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
