# Generated by Django 3.2.12 on 2022-09-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0074_alter_orderitems_position_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='total_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
