# Generated by Django 3.2.12 on 2022-11-23 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0077_auto_20220912_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='datetimes_all',
            field=models.TextField(blank=True, null=True),
        ),
    ]
