# Generated by Django 3.2.12 on 2022-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0078_auto_20221121_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='master_table',
            name='current_datetimes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
