# Generated by Django 3.2.12 on 2022-11-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventsApp', '0080_master_table_current_datetimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='events_positioninfo',
            name='datetimes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
